# Generated by Django 4.1 on 2022-11-01 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=40)),
                ('Phone', models.CharField(blank=True, max_length=40, null=True)),
                ('Website_url', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EduMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MediaChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Website_url', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Website_url', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ToWhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Website_url', models.URLField(max_length=300)),
                ('id_media_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_data.mediachannel')),
            ],
        ),
        migrations.CreateModel(
            name='EduMaterial_towhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_edumaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_data.edumaterial')),
                ('id_towhom', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='edu_data.towhom')),
            ],
        ),
        migrations.CreateModel(
            name='EduMaterial_topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_edumaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_data.edumaterial')),
                ('id_topics', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='edu_data.topics')),
            ],
        ),
        migrations.CreateModel(
            name='EduMaterial_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_edumaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_data.edumaterial')),
                ('id_skill', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='edu_data.skill')),
            ],
        ),
        migrations.CreateModel(
            name='EduMaterial_materialtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_edumaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_data.edumaterial')),
                ('id_materialtype', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='edu_data.materialtype')),
            ],
        ),
        migrations.CreateModel(
            name='EduMaterial_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_edumaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_data.edumaterial')),
                ('id_level', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='edu_data.level')),
            ],
        ),
        migrations.AddField(
            model_name='edumaterial',
            name='id_Institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_data.institution'),
        ),
        migrations.AddField(
            model_name='edumaterial',
            name='id_Media_Channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_data.mediachannel'),
        ),
        migrations.AddField(
            model_name='edumaterial',
            name='id_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_data.author'),
        ),
        migrations.AddField(
            model_name='edumaterial',
            name='id_publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_data.publisher'),
        ),
    ]
