# Generated by Django 4.1 on 2022-10-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EduMaterials',
            new_name='EduMaterial',
        ),
    ]
