# Generated by Django 4.1 on 2022-11-02 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_data', '0002_relatedprojects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edumaterial',
            name='id_Institution',
        ),
        migrations.RemoveField(
            model_name='edumaterial',
            name='id_Media_Channel',
        ),
        migrations.RemoveField(
            model_name='edumaterial',
            name='id_author',
        ),
        migrations.RemoveField(
            model_name='edumaterial',
            name='id_publisher',
        ),
        migrations.RemoveField(
            model_name='edumaterial_level',
            name='id_edumaterial',
        ),
        migrations.RemoveField(
            model_name='edumaterial_level',
            name='id_level',
        ),
        migrations.RemoveField(
            model_name='edumaterial_materialtype',
            name='id_edumaterial',
        ),
        migrations.RemoveField(
            model_name='edumaterial_materialtype',
            name='id_materialtype',
        ),
        migrations.RemoveField(
            model_name='edumaterial_skill',
            name='id_edumaterial',
        ),
        migrations.RemoveField(
            model_name='edumaterial_skill',
            name='id_skill',
        ),
        migrations.RemoveField(
            model_name='edumaterial_topics',
            name='id_edumaterial',
        ),
        migrations.RemoveField(
            model_name='edumaterial_topics',
            name='id_topics',
        ),
        migrations.RemoveField(
            model_name='edumaterial_towhom',
            name='id_edumaterial',
        ),
        migrations.RemoveField(
            model_name='edumaterial_towhom',
            name='id_towhom',
        ),
        migrations.AddField(
            model_name='edumaterial',
            name='Institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_data.institution'),
        ),
        migrations.AddField(
            model_name='edumaterial',
            name='Media_Channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_data.mediachannel'),
        ),
        migrations.AddField(
            model_name='edumaterial',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_data.author'),
        ),
        migrations.AddField(
            model_name='edumaterial',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_data.publisher'),
        ),
        migrations.AddField(
            model_name='edumaterial_level',
            name='edumaterial',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='edu_data.edumaterial'),
        ),
        migrations.AddField(
            model_name='edumaterial_level',
            name='level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='edu_data.level'),
        ),
        migrations.AddField(
            model_name='edumaterial_materialtype',
            name='edumaterial',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='edu_data.edumaterial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edumaterial_materialtype',
            name='materialtype',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='edu_data.materialtype'),
        ),
        migrations.AddField(
            model_name='edumaterial_skill',
            name='edumaterial',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='edu_data.edumaterial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edumaterial_skill',
            name='skill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='edu_data.skill'),
        ),
        migrations.AddField(
            model_name='edumaterial_topics',
            name='edumaterial',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='edu_data.edumaterial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edumaterial_topics',
            name='topics',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='edu_data.topics'),
        ),
        migrations.AddField(
            model_name='edumaterial_towhom',
            name='edumaterial',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='edu_data.edumaterial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edumaterial_towhom',
            name='towhom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='edu_data.towhom'),
        ),
        migrations.AddField(
            model_name='relatedprojects',
            name='edumaterial',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='edu_data.edumaterial'),
        ),
    ]
