# Generated by Django 3.2.5 on 2022-10-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_data', '0003_author_categories_edumaterial_categories_institution_media_channel_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='edumaterial',
            name='id_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_data.author'),
        ),
    ]
