# Generated by Django 4.1 on 2022-11-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_data', '0003_remove_edumaterial_id_institution_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Level',
            new_name='CompetencyLevel',
        ),
    ]
