# Generated by Django 3.2.5 on 2022-10-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_data', '0004_edumaterial_id_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='edumaterial',
            name='id_Institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_data.institution'),
        ),
        migrations.AddField(
            model_name='edumaterial',
            name='id_Media_Channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_data.media_channel'),
        ),
        migrations.AddField(
            model_name='edumaterial',
            name='id_publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_data.publisher'),
        ),
    ]
