# Generated by Django 4.1 on 2022-11-10 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_data', '0004_rename_level_competencylevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='categories',
            new_name='name',
        ),
        migrations.CreateModel(
            name='embeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embeding', models.JSONField(null=True)),
                ('edumaterial', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='edu_data.edumaterial')),
            ],
        ),
    ]
